### ISSUE TITLE
Need to meet this project requirement

### ISSUE THREAD

**Issue by MarcoAZ** [meynmd/cs340#11]
From the final project pdf:
> "It should be possible to add entries to every table (although it is fine to have tables prepopulated with data) and **every table should be used in at least one select query.** If you have complex SELECT queries that feature things like NOT IN, aggregate functions then you don't need the deletes and updates."

I don't think we have anything yet that meets this requirement. I think we could have a view-character page that lists everything: the player, the selected character, character skills, and character items. This will require hitting all the enitity tables as well as relationship tables. I think once that's functional, it might be fun to dazzle it up with a picture of the character class, item, etc.

**Comment by meynmd** [comment]
Yeah, okay! It'll have a lot of columns, but what the hell? Why not.

**Comment by MarcoAZ** [comment]
Only way i could do this was to use COUNT() to get number of items and number of skills. Getting instances of each meant outputting multiple rows of each character:
>Character | Warrior | sword | FireSpell
Character | Warrior | sword | IceSpell
Character | Warrior | shield | FireSpell
Character | Warrior | shield | IceSpell

Not what we want. I guess counts will have to do and I still join to both itemClass and itemInstance but technically we only need to join to one...

**Comment by MarcoAZ** [comment]
I consider this closed unless we want to try something else.
