### ISSUE TITLE
Add Class

### ISSUE THREAD

**Issue by MarcoAZ** [meynmd/cs340#13]
Project requirements state
> "It should be possible to add entries to every table..."

We'll need a way for user to add a custom class to the characterClass table.

**Comment by MarcoAZ** [comment]
Currently, the table looks like this
>  	`id` int NOT NULL AUTO_INCREMENT, 
 	`className` varchar(255) NOT NULL, 
 	`startLevel` tinyint UNSIGNED DEFAULT 1, 
 	`startHealth` smallint UNSIGNED DEFAULT 100, 
 	`startStrength` smallint UNSIGNED NOT NULL, 

We could add another default to 'startStrength' and that way all custom classes start equally or we could allow users to enter their starting level, health, strength. The latter means we would have to validate user inputs so they don't overflow tinyint/smallint. Work-wise, it would be easy to just use defaults. But if really want to give the option, we can use a dropdown menu of presets and not worry about validation.

**Comment by meynmd** [comment]
I suspect we can just check the box on this requirement: let the user enter a class name and don't give them any more options than that. But if you really want to, we could do something more complicated.

**Comment by MarcoAZ** [comment]
Nope, I agree.

**Comment by meynmd** [comment]
Okay, how does that look?

**Comment by MarcoAZ** [comment]
This is done right? Close?
