### ISSUE TITLE
skillCount and itemCount

### ISSUE THREAD

**Issue by meynmd** [meynmd/cs340#20]
Marco, were skillCount and itemCount working before? I was copying viewCharacter.php to make a page called viewPlayer.php--basically the same thing, but listing every character belonging to a player--when I noticed that neither column was working. They always said zero. I got skillCount working, but haven't had a chance to look at itemCount yet.

**Comment by MarcoAZ** [comment]
They were definitely working. I tested it after adding and removing items.

**Comment by meynmd** [comment]
Hmm. I hope I didn't break it. Well, anyway, I've got it working again! I haven't messed with viewCharacter (not as far as I can remember anyway), but the counts are working in viewPlayer.php

**Comment by meynmd** [comment]
In fact, we could just have the character names link to viewPlayer.php since it contains the same info, just with every character belonging to that player instead of one specific character.

**Comment by MarcoAZ** [comment]
I see what you mean. It shows item counts for new characters I've created but not for ones created in the sql file.

**Comment by MarcoAZ** [comment]
So weird. I just took the query from viewPlayer and copied it to viewCharacter. Seems to work for everyone now.
