### ISSUE TITLE
delete character

### ISSUE THREAD

**Issue by meynmd** [meynmd/cs340#32]
We've got so many pages in our project now that I can't remember what all is in there--do we have the ability to delete a character?

**Comment by MarcoAZ** [comment]
Wow, I don't think so.

**Comment by meynmd** [comment]
I added a form to delete a character from the user's list of characters (and a file deleteCharacter.php to actually do it). I also made the dropdown lists show only the class names for adding a character and only the character names for deleting because it seemed unnecessary to show the numeric id. If you disagree, Marco, just uncomment the line--playerCharacters.php 135, I think it is.

**Comment by MarcoAZ** [comment]
It's great!
