### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by meynmd** [meynmd/cs340#33]
I guess it's time to gather the pieces we need for this project, so I'll start issues for the parts from the assignment we don't have yet:

Outline (5%)
Give me a paragraph or two explaining your database content. If it is about auto dealerships, tell me
what goes on at the auto dealership and why it would be interesting to track that data.

**Comment by MarcoAZ** [comment]
I assigned myself and commented on the wrong one :) check out outline.docx

**Comment by meynmd** [comment]
Looks good! I added a line or two and saved it as outline_1_1.docx

**Comment by MarcoAZ** [comment]
Looks good!
